#!/bin/bash -e

. $(dirname $0)/addPath

assertEquals() {
  local expected=$1
  local version=$2
  version=$(debUpver "$version")
  if [ "$version" != "$expected" ]; then
    echo 1>&2 "Result differs from expected:"
    echo 1>&2 "Expected: ${expected}"
    echo 1>&2 "Actual: ${version}"
    exit 1
  fi
}

assertEquals '2.0.0' '2.0.0'

assertEquals '2.0.0' '2.0.0-1'
assertEquals '2.0.0' '2.0.0-1.1'

assertEquals '2.0.0' '0:2.0.0'
assertEquals '2.0.0' '1:2.0.0'
assertEquals '2.0.0' '1.1:2.0.0'
assertEquals '2.0.0' '1-1:2.0.0'

assertEquals '2.0.0' '0:2.0.0-1'
assertEquals '2.0.0' '1:2.0.0-1.1'
assertEquals '2.0.0' '1.1:2.0.0-1.1'
assertEquals '2.0.0' '1-1:2.0.0-1.1'

assertEquals '2.0.0-1' '2.0.0-1-2'
assertEquals '2.0.0-1' '1:2.0.0-1-2'
assertEquals '2.0.0-1' '1-1:2.0.0-1-2'
