#!/bin/bash -e

## enable colors with "--color"
if [[ "$1" = "--color" ]]; then
  RED='\e[31m'
  GREEN='\e[32m'
  NC='\e[0m'
else
  RED=''
  GREEN=''
  NC=''
fi

dir=$(dirname $0)
exit=0

runTest() {
  local file=$1
  [[ -x "$file" ]] || return
  if $file > /dev/null; then
    echo -e "${file}: ${GREEN}passed${NC}"
  else
    echo -e 1>&2 "${file}: ${RED}failed ($?)${NC}"
    exit=1
  fi
}

runDir() {
  local dir=$1
  echo "Running tests in ${dir}"
  readAnd runTest < <(find "$dir" -maxdepth 1 -type f -executable ! -samefile "$0")
  readAnd runDir < <(find "$dir" -maxdepth 1 -type d -executable ! -samefile "$dir")
}

readAnd() {
  local cmd=$1
  local line
  while read -r line; do
    $cmd "$line"
  done
}

runDir "$dir"

exit $exit
