#!/bin/bash -e

version=1.2.3
pattern='([^[:alnum:]]*)([0-9]+)$'

if [[ "$version" =~ $pattern ]]; then
  echo "BASH_REMATCH[0]: ${BASH_REMATCH[0]}"
  echo "BASH_REMATCH[1]: ${BASH_REMATCH[1]}"
  echo "BASH_REMATCH[2]: ${BASH_REMATCH[2]}"
  version=${version:0:-${#BASH_REMATCH[0]}}
  echo "$version"
else
  echo "no match"
fi
