name: Bash Actions
description: Bash scripts to use in a workflow
runs:
  using: composite
  steps:
    - name: Export path
      shell: bash
      run: echo "${GITHUB_ACTION_PATH}/bin" >> $GITHUB_PATH
