#!/bin/bash

. bash-functions

V_FILE="package.json"

getVersion() {
  local version=$(npm pkg get version)
  echo "${version:1:-1}"
}

setVersion() {
  local version=$1
  npm pkg set version="${version}"
}
