#!/bin/bash -e

. $(dirname $0)/_commitsVersionIndex

newTest "Disable index commits"

COMMITS_FIX_INDEX=-1

addCommit <<< "dev: some development"
addCommit <<< "dev: some more development"
addCommit <<< "fix: fix some bug"
addCommit <<< "dev: even more development"

assertEquals '' $index
