#!/bin/bash -e

. $(dirname $0)/_commitsVersionIndex

newTest "Redefine standard indexes"

V_MAJOR=1
V_MINOR=0

addCommit <<< "fix: fixed a bug"

assertEquals 0 $index

addCommit <<< "feat: a nice, non breaking feature"

assertEquals 0 $index

addCommit <<< "feat!: add some breaking feature"

assertEquals 1 $index
