#!/bin/bash

. $(dirname $0)/../../_tests

## include createChangelog internals, ignoring input and output
. debCreateChangelog < /dev/null > /dev/null

commitId=0
declare -A COMMIT_MAP

## override `getCommitBody` from `commitparser`
## this allows to create fake commits, works in tandem with `addCommit`
getCommitBody() {
  local commit=$1
  echo "${COMMIT_MAP[$commit]}"
}

addCommit() {
  local body=$(cat)
  (( ++commitId ))
  COMMIT_MAP[$commitId]=$body
  ## simulate `commitstree` script
  parseCommit "$commitId"
  __commitstree_addCommit "$commitId"
}

## simulate `createChangelog` script
createChangelog() {
  writeChangelogBody
}
