#!/bin/bash -e

. $(dirname $0)/_debCreateChangelog

addCommit <<< "feat: add some feature"
addCommit <<< "feat: add some other feature"
addCommit <<< "fix: avoid division by 0"
addCommit <<< "feat!: add some breaking feature"
addCommit <<< "fix: tight the screw"
addCommit <<< "feat: another breaking change

BREAKING CHANGE: feature X will not work anymore
"

createChangelog
